# Generated by Django 5.1.1 on 2024-10-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Author_Name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('Date_of_publish', models.DateField()),
            ],
        ),
    ]
